#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# PowerFinger - Copy the current Shenzhen / Seeed send-or-link packet locally.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
packet_doc="docs/sensors-converge-2026/SHENZHEN-SEEED-QUOTE-PACKET.md"
first_contact_template="docs/sensors-converge-2026/SHENZHEN-FIRST-CONTACT-TEMPLATE.md"
factory_one_pager="docs/sensors-converge-2026/SHENZHEN-FACTORY-ONE-PAGER.zh-CN.md"
default_output="$repo_root/build/quote-packets/shenzhen-seeed-usb-hub-current"
include_r30_annex=0

usage() {
    cat <<'EOF'
Usage:
  scripts/export-shenzhen-seeed-quote-packet.sh [--include-r30-annex] [output-dir]

Copies exactly the paths listed under "USB-HUB Send-Now Source Files To Send Or
Link" in docs/sensors-converge-2026/SHENZHEN-SEEED-QUOTE-PACKET.md and writes a
local PACKET-MANIFEST.md with file sizes and SHA-256 hashes. Also regenerates
the USB-HUB local fabrication-review bundle and includes it under
USB-HUB-FABRICATION-REVIEW/.
The export root includes OUTBOUND-DRAFT.md with subject/body placeholders and
ATTACHMENT-MANIFEST.md with the send list derived from the same packet sections.
The default hub packet must include SHENZHEN-FACTORY-RESPONSE-CAPTURE.md so
factory replies can be pasted back without mixing quote-only and verified state.
The regenerated USB-HUB fabrication-review archive must match the SHA-256
recorded in hardware/shared/USB-HUB/kicad/FABRICATION-OUTPUTS.md.

With --include-r30-annex, also copies the "R30-OLED-NONE-NONE DFM / Pre-Fab
Review Annex Files" list under R30-OLED-NONE-NONE-DFM-ANNEX/. That annex must
include hardware/ring/R30-OLED-NONE-NONE/kicad/CURRENT-VIOLATIONS.md because it
is the checked-in source for the quote-facing R30 KiCad status, and
hardware/ring/R30-OLED-NONE-NONE/kicad/FABRICATION-OUTPUTS.md because it records
the local generated-output review, and
hardware/ring/R30-OLED-NONE-NONE/kicad/BOARD-HOUSE-OUTPUT-CONSTRAINTS.md because
it records the output-constraints questions that keep the ring blocker specific.

With no output directory, regenerates:
  build/quote-packets/shenzhen-seeed-usb-hub-current

Default send-ready hub quote packet:
  build/quote-packets/shenzhen-seeed-usb-hub-current

Optional R30 DFM/pre-fab annex with --include-r30-annex:
  build/quote-packets/shenzhen-seeed-usb-hub-current/R30-OLED-NONE-NONE-DFM-ANNEX
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

extract_recorded_archive_sha256() {
    sed -n '/^Archive SHA-256:$/{
        n
        s/^`\([0-9a-f][0-9a-f]*\)`$/\1/p
        q
    }' "$1"
}

args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --include-r30-annex)
            include_r30_annex=1
            shift
            ;;
        --*)
            usage >&2
            exit 2
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

if [[ "${#args[@]}" -gt 1 ]]; then
    usage >&2
    exit 2
fi

output_dir="${args[0]:-$default_output}"
case "$output_dir" in
    /*) ;;
    *) output_dir="$repo_root/$output_dir" ;;
esac

packet_path="$repo_root/$packet_doc"
[[ -f "$packet_path" ]] || die "quote packet document is missing: $packet_doc"

read_doc_section() {
    local heading="$1"
    awk '
        $0 == heading { in_section = 1; next }
        in_section && /^## / { exit }
        in_section { print }
    ' heading="## $heading" "$packet_path" | sed -n 's/^- `\([^`]*\)`.*/\1/p'
}

read_markdown_section() {
    local rel_path="$1"
    local heading="$2"
    awk '
        $0 == heading { in_section = 1; next }
        in_section && /^## / { exit }
        in_section { print }
    ' heading="## $heading" "$repo_root/$rel_path"
}

write_outbound_draft() {
    local dest="$output_dir/OUTBOUND-DRAFT.md"
    local subject
    local message

    subject="$(read_markdown_section "$first_contact_template" "Subject" | sed '/^[[:space:]]*$/d')"
    message="$(read_markdown_section "$first_contact_template" "Message")"

    [[ -n "$subject" ]] || die "could not read Subject from $first_contact_template"
    [[ -n "$message" ]] || die "could not read Message from $first_contact_template"

    if [[ "$include_r30_annex" -eq 0 ]]; then
        message="$(printf '%s\n' "$message" | awk '
            /^linked source packet under two separate scopes:$/ {
                print "linked source packet for the `USB-HUB` send-now quote path:"
                next
            }
            /^2\. `R30-OLED-NONE-NONE` optional annex$/ {
                skip = 1
                next
            }
            skip && /^Please keep any proposed substitutions explicit:/ {
                skip = 0
            }
            !skip {
                print
            }
        ')"
    fi

    {
        printf '<!-- SPDX-License-Identifier: CC-BY-SA-4.0 -->\n'
        printf '# Shenzhen / Seeed Outbound Draft\n\n'
        printf 'Generated by `scripts/export-shenzhen-seeed-quote-packet.sh` from `%s`.\n' "$first_contact_template"
        printf 'Replace placeholders before sending; do not add readiness, yield, certification, OCR, companion-app, or secondary-variant claims unless a current packet source file backs them.\n\n'
        printf '## Subject\n\n'
        printf '%s\n\n' "$subject"
        printf '## Body\n\n'
        printf '%s\n\n' "$message"
        printf '## Placeholder Checklist\n\n'
        printf '%s\n' '- Replace `[factory / Seeed contact]`.'
        printf '%s\n' '- Replace `[name]`.'
        printf '%s\n' '- Replace `[project/repo link or source packet link]`.'
        printf '%s\n' '- Replace `[preferred contact channel]`.'
        printf '%s\n\n' '- Use `ATTACHMENT-MANIFEST.md` as the send list and `PACKET-MANIFEST.md` as the hash manifest.'
        printf '## Honest Status Notes\n\n'
        printf '%s\n' '- `USB-HUB` is the send-now quote path for PCB fabrication/assembly plus connector/enclosure DFM review.'
        printf '%s\n' '- Printed host fit, adjacent-port clearance, clamp-hole alignment, service-hatch reach, connector-retention evidence, yield, lead time, and realized COGS are not measured by this export.'
        if [[ "$include_r30_annex" -eq 1 ]]; then
            printf '%s\n' '- `R30-OLED-NONE-NONE-DFM-ANNEX/` is included only for DFM/pre-fab review; do not request ring PCB fabrication or assembly from it.'
        else
            printf '%s\n' '- The R30 ring annex is omitted. Rerun with `--include-r30-annex` only if the factory explicitly accepts DFM/pre-fab review.'
        fi
    } > "$dest"
}

write_attachment_manifest() {
    local dest="$output_dir/ATTACHMENT-MANIFEST.md"

    {
        printf '<!-- SPDX-License-Identifier: MIT -->\n'
        printf '# Shenzhen / Seeed Attachment Manifest\n\n'
        printf 'Generated by `scripts/export-shenzhen-seeed-quote-packet.sh` from `%s`.\n' "$packet_doc"
        printf 'This send list is derived from the packet document sections at export time; `PACKET-MANIFEST.md` records byte counts and SHA-256 hashes for the generated bundle.\n\n'
        printf '## Send-Now USB-HUB Quote Attachments\n\n'
        printf 'Status: attach or link these for the `USB-HUB` PCB fab/assembly quote, connector/enclosure DFM review, and serviceability feedback. This is not measured physical-fit, yield, lead-time, or realized-COGS evidence.\n\n'
        printf '| Attachment | Scope |\n'
        printf '|---|---|\n'
        for rel_path in "${packet_files[@]}"; do
            printf '| `%s` | Listed in `%s` under `%s`. |\n' "$rel_path" "$packet_doc" "$hub_section"
        done
        printf '| `USB-HUB-FABRICATION-REVIEW/` | Regenerated hub Gerber/drill/POS/BOM review bundle; archive hash must match `%s`. |\n' "$hub_fabrication_outputs"
        printf '\n## Optional R30 DFM / Pre-Fab Annex\n\n'
        if [[ "$include_r30_annex" -eq 1 ]]; then
            printf 'Status: included because `--include-r30-annex` was used. Send only when the factory explicitly accepts DFM/pre-fab review; do not request ring PCB fabrication or assembly from these files.\n\n'
            printf '| Attachment | Scope |\n'
            printf '|---|---|\n'
            for rel_path in "${r30_annex_files[@]}"; do
                printf '| `R30-OLED-NONE-NONE-DFM-ANNEX/%s` | Listed in `%s` under `%s`; annex-only DFM/pre-fab review. |\n' "$rel_path" "$packet_doc" "$r30_section"
            done
        else
            printf 'Status: omitted from this export. To generate it, rerun `scripts/export-shenzhen-seeed-quote-packet.sh --include-r30-annex` after the factory accepts DFM/pre-fab review.\n'
        fi
        printf '\n## Operator Files\n\n'
        printf '%s\n' '- `OUTBOUND-DRAFT.md` is the generated email draft with subject/body placeholders.'
        printf '%s\n' '- `ATTACHMENT-MANIFEST.md` is this send list.'
        printf '%s\n' '- `PACKET-MANIFEST.md` is the hash manifest for copied and generated files.'
    } > "$dest"
}

hub_section="USB-HUB Send-Now Source Files To Send Or Link"
r30_section="R30-OLED-NONE-NONE DFM / Pre-Fab Review Annex Files"
hub_fabrication_outputs="hardware/shared/USB-HUB/kicad/FABRICATION-OUTPUTS.md"
hub_output_constraints="hardware/shared/USB-HUB/kicad/BOARD-HOUSE-OUTPUT-CONSTRAINTS.md"
hub_fabrication_script="scripts/generate-usb-hub-fabrication-review.py"
hub_fabrication_review_dir="build-kicad/USB-HUB/fabrication-review"
hub_fabrication_archive="build-kicad/USB-HUB/usb-hub-fabrication-review.zip"
r30_status_source="hardware/ring/R30-OLED-NONE-NONE/kicad/CURRENT-VIOLATIONS.md"
r30_fabrication_outputs="hardware/ring/R30-OLED-NONE-NONE/kicad/FABRICATION-OUTPUTS.md"
r30_output_constraints="hardware/ring/R30-OLED-NONE-NONE/kicad/BOARD-HOUSE-OUTPUT-CONSTRAINTS.md"
response_capture="docs/sensors-converge-2026/SHENZHEN-FACTORY-RESPONSE-CAPTURE.md"

packet_files=()
while IFS= read -r rel_path; do
    packet_files+=("$rel_path")
done < <(read_doc_section "$hub_section")
generated_review_files=0

[[ "${#packet_files[@]}" -gt 0 ]] || die "no source files found in $packet_doc section: $hub_section"

has_hub_fabrication_outputs=0
has_hub_output_constraints=0
has_hub_fabrication_script=0
has_first_contact_template=0
has_factory_one_pager=0
for rel_path in "${packet_files[@]}"; do
    [[ "$rel_path" == "$hub_fabrication_outputs" ]] && has_hub_fabrication_outputs=1
    [[ "$rel_path" == "$hub_output_constraints" ]] && has_hub_output_constraints=1
    [[ "$rel_path" == "$hub_fabrication_script" ]] && has_hub_fabrication_script=1
    [[ "$rel_path" == "$first_contact_template" ]] && has_first_contact_template=1
    [[ "$rel_path" == "$factory_one_pager" ]] && has_factory_one_pager=1
done
[[ "$has_hub_fabrication_outputs" -eq 1 ]] || die "USB-HUB send-now packet must include checked-in fabrication output review: $hub_fabrication_outputs"
[[ "$has_hub_output_constraints" -eq 1 ]] || die "USB-HUB send-now packet must include board-house output constraints: $hub_output_constraints"
[[ "$has_hub_fabrication_script" -eq 1 ]] || die "USB-HUB send-now packet must include fabrication-review generator: $hub_fabrication_script"
[[ "$has_first_contact_template" -eq 1 ]] || die "USB-HUB send-now packet must include first-contact template: $first_contact_template"
[[ "$has_factory_one_pager" -eq 1 ]] || die "USB-HUB send-now packet must include factory one-pager: $factory_one_pager"

has_response_capture=0
for rel_path in "${packet_files[@]}"; do
    if [[ "$rel_path" == "$response_capture" ]]; then
        has_response_capture=1
        break
    fi
done
[[ "$has_response_capture" -eq 1 ]] || die "hub packet must include response-capture form: $response_capture"

r30_annex_files=()
if [[ "$include_r30_annex" -eq 1 ]]; then
    while IFS= read -r rel_path; do
        r30_annex_files+=("$rel_path")
    done < <(read_doc_section "$r30_section")
    [[ "${#r30_annex_files[@]}" -gt 0 ]] || die "no source files found in $packet_doc section: $r30_section"

    has_r30_status_source=0
    for rel_path in "${r30_annex_files[@]}"; do
        if [[ "$rel_path" == "$r30_status_source" ]]; then
            has_r30_status_source=1
            break
        fi
    done
    [[ "$has_r30_status_source" -eq 1 ]] || die "R30 annex must include checked-in status source: $r30_status_source"

    has_r30_fabrication_outputs=0
    for rel_path in "${r30_annex_files[@]}"; do
        if [[ "$rel_path" == "$r30_fabrication_outputs" ]]; then
            has_r30_fabrication_outputs=1
            break
        fi
    done
    [[ "$has_r30_fabrication_outputs" -eq 1 ]] || die "R30 annex must include checked-in fabrication output review: $r30_fabrication_outputs"

    has_r30_output_constraints=0
    for rel_path in "${r30_annex_files[@]}"; do
        if [[ "$rel_path" == "$r30_output_constraints" ]]; then
            has_r30_output_constraints=1
            break
        fi
    done
    [[ "$has_r30_output_constraints" -eq 1 ]] || die "R30 annex must include board-house output constraints: $r30_output_constraints"
fi

missing=()
for rel_path in "${packet_files[@]}"; do
    if [[ ! -f "$repo_root/$rel_path" ]]; then
        missing+=("$rel_path")
    fi
done
for rel_path in "${r30_annex_files[@]}"; do
    if [[ ! -f "$repo_root/$rel_path" ]]; then
        missing+=("$rel_path")
    fi
done

if [[ "${#missing[@]}" -gt 0 ]]; then
    printf 'error: quote packet lists missing files:\n' >&2
    printf '  %s\n' "${missing[@]}" >&2
    exit 1
fi

if [[ "$output_dir" == "$repo_root" || "$output_dir" == "/" ]]; then
    die "refusing to export into $output_dir"
fi

if [[ "$output_dir" == "$default_output" ]]; then
    rm -rf "$output_dir"
elif [[ -d "$output_dir" ]] && find "$output_dir" -mindepth 1 -maxdepth 1 | grep -q .; then
    die "custom output directory is not empty: $output_dir"
fi

mkdir -p "$output_dir"

(cd "$repo_root" && "$hub_fabrication_script")
[[ -d "$repo_root/$hub_fabrication_review_dir" ]] || die "USB-HUB fabrication review directory was not generated: $hub_fabrication_review_dir"
[[ -f "$repo_root/$hub_fabrication_archive" ]] || die "USB-HUB fabrication review archive was not generated: $hub_fabrication_archive"
recorded_hub_archive_sha256="$(extract_recorded_archive_sha256 "$repo_root/$hub_fabrication_outputs")"
[[ "${#recorded_hub_archive_sha256}" -eq 64 ]] || die "could not read archive SHA-256 from $hub_fabrication_outputs"
actual_hub_archive_sha256="$(shasum -a 256 "$repo_root/$hub_fabrication_archive" | awk '{ print $1 }')"
[[ "$actual_hub_archive_sha256" == "$recorded_hub_archive_sha256" ]] || die "USB-HUB fabrication review archive hash drifted: generated $actual_hub_archive_sha256, recorded $recorded_hub_archive_sha256 in $hub_fabrication_outputs"

write_outbound_draft
write_attachment_manifest
attachment_rows="$(grep -c '^| `' "$output_dir/ATTACHMENT-MANIFEST.md")"
expected_attachment_rows=$((${#packet_files[@]} + 1 + ${#r30_annex_files[@]}))
[[ "$attachment_rows" -eq "$expected_attachment_rows" ]] || die "attachment manifest row count drifted: expected $expected_attachment_rows rows, found $attachment_rows"

manifest="$output_dir/PACKET-MANIFEST.md"
{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# Shenzhen / Seeed Quote Packet Export Manifest\n\n'
    printf 'Generated by `scripts/export-shenzhen-seeed-quote-packet.sh` from `%s`.\n\n' "$packet_doc"
    printf 'Scope: copied exactly from the packet document section `%s`.' "$hub_section"
    if [[ "$include_r30_annex" -eq 1 ]]; then
        printf ' Also copied `%s` under `R30-OLED-NONE-NONE-DFM-ANNEX/` for DFM/pre-fab review only.' "$r30_section"
    fi
    printf ' The USB-HUB fabrication-review bundle is regenerated and copied under `USB-HUB-FABRICATION-REVIEW/`.\n\n'
    printf '| Path | Bytes | SHA-256 |\n'
    printf '|---|---:|---|\n'
} > "$manifest"

for rel_path in OUTBOUND-DRAFT.md ATTACHMENT-MANIFEST.md; do
    src="$output_dir/$rel_path"
    bytes="$(wc -c < "$src" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$src" | awk '{ print $1 }')"
    printf '| `%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256" >> "$manifest"
done

for rel_path in "${packet_files[@]}"; do
    src="$repo_root/$rel_path"
    dest="$output_dir/$rel_path"
    mkdir -p "$(dirname "$dest")"
    cp -p "$src" "$dest"

    bytes="$(wc -c < "$src" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$src" | awk '{ print $1 }')"
    printf '| `%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256" >> "$manifest"
done

while IFS= read -r generated_path; do
    generated_review_files=$((generated_review_files + 1))
    rel_generated="${generated_path#"$repo_root/"}"
    rel_inside_review="${rel_generated#"$hub_fabrication_review_dir/"}"
    dest="$output_dir/USB-HUB-FABRICATION-REVIEW/$rel_inside_review"
    mkdir -p "$(dirname "$dest")"
    cp -p "$generated_path" "$dest"

    bytes="$(wc -c < "$generated_path" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$generated_path" | awk '{ print $1 }')"
    printf '| `USB-HUB-FABRICATION-REVIEW/%s` | %s | `%s` |\n' "$rel_inside_review" "$bytes" "$sha256" >> "$manifest"
done < <(find "$repo_root/$hub_fabrication_review_dir" -type f | sort)

hub_archive_dest="$output_dir/USB-HUB-FABRICATION-REVIEW/usb-hub-fabrication-review.zip"
cp -p "$repo_root/$hub_fabrication_archive" "$hub_archive_dest"
hub_archive_bytes="$(wc -c < "$repo_root/$hub_fabrication_archive" | tr -d '[:space:]')"
hub_archive_sha256="$actual_hub_archive_sha256"
printf '| `USB-HUB-FABRICATION-REVIEW/usb-hub-fabrication-review.zip` | %s | `%s` |\n' "$hub_archive_bytes" "$hub_archive_sha256" >> "$manifest"
generated_review_files=$((generated_review_files + 1))

if [[ "$include_r30_annex" -eq 1 ]]; then
    for rel_path in "${r30_annex_files[@]}"; do
        src="$repo_root/$rel_path"
        dest="$output_dir/R30-OLED-NONE-NONE-DFM-ANNEX/$rel_path"
        mkdir -p "$(dirname "$dest")"
        cp -p "$src" "$dest"

        bytes="$(wc -c < "$src" | tr -d '[:space:]')"
        sha256="$(shasum -a 256 "$src" | awk '{ print $1 }')"
        printf '| `R30-OLED-NONE-NONE-DFM-ANNEX/%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256" >> "$manifest"
    done
fi

total_files=$((${#packet_files[@]} + generated_review_files + ${#r30_annex_files[@]} + 2))
manifest_rows="$(grep -c '^| `' "$manifest")"
[[ "$manifest_rows" -eq "$total_files" ]] || die "manifest row count drifted: expected $total_files rows, found $manifest_rows"
exported_files="$(find "$output_dir" -type f ! -name 'PACKET-MANIFEST.md' | wc -l | tr -d '[:space:]')"
[[ "$exported_files" -eq "$total_files" ]] || die "exported file count drifted: expected $total_files files plus manifest, found $exported_files files plus manifest"

printf 'Exported %s files to %s\n' "$total_files" "$output_dir"
printf 'Manifest: %s\n' "$manifest"
printf 'Self-check: manifest rows, exported file count, and USB-HUB fabrication-review archive hash match.\n'
printf 'Outbound draft: %s\n' "$output_dir/OUTBOUND-DRAFT.md"
printf 'Attachment manifest: %s\n' "$output_dir/ATTACHMENT-MANIFEST.md"
printf 'Send-ready hub quote packet: %s\n' "$output_dir"
printf 'USB-HUB fabrication review: %s\n' "$output_dir/USB-HUB-FABRICATION-REVIEW"
if [[ "$include_r30_annex" -eq 1 ]]; then
    printf 'Optional R30 DFM/pre-fab annex: %s\n' "$output_dir/R30-OLED-NONE-NONE-DFM-ANNEX"
else
    printf 'Optional R30 annex: rerun with --include-r30-annex when the factory accepts pre-fab review.\n'
fi
