#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# PowerFinger - Copy the current Shenzhen / Seeed send-or-link packet locally.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
packet_doc="docs/sensors-converge-2026/SHENZHEN-SEEED-QUOTE-PACKET.md"
default_output="$repo_root/build/quote-packets/shenzhen-seeed-usb-hub-current"
include_r30_annex=0

usage() {
    cat <<'EOF'
Usage:
  scripts/export-shenzhen-seeed-quote-packet.sh [--include-r30-annex] [output-dir]

Copies exactly the paths listed under "USB-HUB Send-Now Source Files To Send Or
Link" in docs/sensors-converge-2026/SHENZHEN-SEEED-QUOTE-PACKET.md and writes a
local PACKET-MANIFEST.md with file sizes and SHA-256 hashes.

With --include-r30-annex, also copies the "R30-OLED-NONE-NONE DFM / Pre-Fab
Review Annex Files" list under R30-OLED-NONE-NONE-DFM-ANNEX/.

With no output directory, regenerates:
  build/quote-packets/shenzhen-seeed-usb-hub-current
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --include-r30-annex)
            include_r30_annex=1
            shift
            ;;
        --*)
            usage >&2
            exit 2
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

if [[ "${#args[@]}" -gt 1 ]]; then
    usage >&2
    exit 2
fi

output_dir="${args[0]:-$default_output}"
case "$output_dir" in
    /*) ;;
    *) output_dir="$repo_root/$output_dir" ;;
esac

packet_path="$repo_root/$packet_doc"
[[ -f "$packet_path" ]] || die "quote packet document is missing: $packet_doc"

read_doc_section() {
    local heading="$1"
    awk '
        $0 == heading { in_section = 1; next }
        in_section && /^## / { exit }
        in_section { print }
    ' heading="## $heading" "$packet_path" | sed -n 's/^- `\([^`]*\)`.*/\1/p'
}

hub_section="USB-HUB Send-Now Source Files To Send Or Link"
r30_section="R30-OLED-NONE-NONE DFM / Pre-Fab Review Annex Files"

packet_files=()
while IFS= read -r rel_path; do
    packet_files+=("$rel_path")
done < <(read_doc_section "$hub_section")

[[ "${#packet_files[@]}" -gt 0 ]] || die "no source files found in $packet_doc section: $hub_section"

r30_annex_files=()
if [[ "$include_r30_annex" -eq 1 ]]; then
    while IFS= read -r rel_path; do
        r30_annex_files+=("$rel_path")
    done < <(read_doc_section "$r30_section")
    [[ "${#r30_annex_files[@]}" -gt 0 ]] || die "no source files found in $packet_doc section: $r30_section"
fi

missing=()
for rel_path in "${packet_files[@]}"; do
    if [[ ! -f "$repo_root/$rel_path" ]]; then
        missing+=("$rel_path")
    fi
done
for rel_path in "${r30_annex_files[@]}"; do
    if [[ ! -f "$repo_root/$rel_path" ]]; then
        missing+=("$rel_path")
    fi
done

if [[ "${#missing[@]}" -gt 0 ]]; then
    printf 'error: quote packet lists missing files:\n' >&2
    printf '  %s\n' "${missing[@]}" >&2
    exit 1
fi

if [[ "$output_dir" == "$repo_root" || "$output_dir" == "/" ]]; then
    die "refusing to export into $output_dir"
fi

if [[ "$output_dir" == "$default_output" ]]; then
    rm -rf "$output_dir"
elif [[ -d "$output_dir" ]] && find "$output_dir" -mindepth 1 -maxdepth 1 | grep -q .; then
    die "custom output directory is not empty: $output_dir"
fi

mkdir -p "$output_dir"

manifest="$output_dir/PACKET-MANIFEST.md"
{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# Shenzhen / Seeed Quote Packet Export Manifest\n\n'
    printf 'Generated by `scripts/export-shenzhen-seeed-quote-packet.sh` from `%s`.\n\n' "$packet_doc"
    printf 'Scope: copied exactly from the packet document section `%s`.' "$hub_section"
    if [[ "$include_r30_annex" -eq 1 ]]; then
        printf ' Also copied `%s` under `R30-OLED-NONE-NONE-DFM-ANNEX/` for DFM/pre-fab review only.' "$r30_section"
    fi
    printf ' No Gerbers, STLs, archives, or other derived fabrication artifacts are generated.\n\n'
    printf '| Path | Bytes | SHA-256 |\n'
    printf '|---|---:|---|\n'
} > "$manifest"

for rel_path in "${packet_files[@]}"; do
    src="$repo_root/$rel_path"
    dest="$output_dir/$rel_path"
    mkdir -p "$(dirname "$dest")"
    cp -p "$src" "$dest"

    bytes="$(wc -c < "$src" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$src" | awk '{ print $1 }')"
    printf '| `%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256" >> "$manifest"
done

if [[ "$include_r30_annex" -eq 1 ]]; then
    for rel_path in "${r30_annex_files[@]}"; do
        src="$repo_root/$rel_path"
        dest="$output_dir/R30-OLED-NONE-NONE-DFM-ANNEX/$rel_path"
        mkdir -p "$(dirname "$dest")"
        cp -p "$src" "$dest"

        bytes="$(wc -c < "$src" | tr -d '[:space:]')"
        sha256="$(shasum -a 256 "$src" | awk '{ print $1 }')"
        printf '| `R30-OLED-NONE-NONE-DFM-ANNEX/%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256" >> "$manifest"
    done
fi

total_files=$((${#packet_files[@]} + ${#r30_annex_files[@]}))
printf 'Exported %s files to %s\n' "$total_files" "$output_dir"
printf 'Manifest: %s\n' "$manifest"
