#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# PowerFinger - Regenerate USB-HUB quick-print validation coupons locally.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_scad="hardware/shared/USB-HUB/cad/usb_hub_enclosure_blank.scad"
default_output="$repo_root/build/usb-hub-mechanical"

usage() {
    cat <<'EOF'
Usage:
  scripts/generate-usb-hub-validation-coupons.sh [output-dir]

Regenerates the USB-HUB OpenSCAD validation coupon STLs, preview PNGs, local
manifests, and physical-check worksheet scaffolding for the next direct-plug
hub check.

With no output directory, regenerates:
  build/usb-hub-mechanical

The generated files are local print/preview artifacts only. They do not prove
physical USB-A seating, adjacent-port clearance, clamp loading, hatch reach, or
connector strain until printed and checked against real hardware.
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 2
fi

command -v openscad >/dev/null 2>&1 || die "openscad is not on PATH"

output_dir="${1:-$default_output}"
case "$output_dir" in
    /*) ;;
    *) output_dir="$repo_root/$output_dir" ;;
esac

[[ -f "$repo_root/$source_scad" ]] || die "missing OpenSCAD source: $source_scad"
[[ "$output_dir" != "$repo_root" && "$output_dir" != "/" ]] || die "refusing to export into $output_dir"

if [[ "$output_dir" == "$default_output" ]]; then
    rm -rf "$output_dir"
elif [[ -d "$output_dir" ]] && find "$output_dir" -mindepth 1 -maxdepth 1 | grep -q .; then
    die "custom output directory is not empty: $output_dir"
fi

mkdir -p "$output_dir"
preview_dir="$output_dir/previews"
mkdir -p "$preview_dir"

declare -a coupons=(
    "host_fit_coupon|usb-hub-host-fit-coupon.stl"
    "clamp_alignment_gauge|usb-hub-clamp-alignment-gauge.stl"
    "service_hatch_reach_gauge|usb-hub-service-hatch-reach-gauge.stl"
    "validation_set|usb-hub-validation-set.stl"
)

openscad_version="$(openscad --version 2>&1 | head -n 1)"
generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
manifest="$output_dir/COUPON-MANIFEST.md"
worksheet="$output_dir/PHYSICAL-CHECK-WORKSHEET.md"
readme="$output_dir/README.md"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Mechanical Print / Preview Bundle\n\n'
    printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf '%s\n' "- Source: \`$source_scad\`"
    printf '%s\n' "- OpenSCAD: \`$openscad_version\`"
    printf '%s\n\n' "- Scope: generated STL and PNG preview artifacts only; no physical fit, strain, or clearance measurements are claimed here."
    printf '| Export mode | Print artifact | Print bytes | Print SHA-256 | Preview artifact | Preview bytes | Preview SHA-256 | OpenSCAD result |\n'
    printf '|---|---|---:|---|---|---:|---|---|\n'
} > "$manifest"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Physical Coupon Check Worksheet\n\n'
    printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf 'Use this worksheet after printing the generated STLs. Leave rows blank until a real board, board blank, host port, tool, or printed coupon has been checked. Do not mark a pass from CAD generation or PNG preview alone.\n\n'
    printf '| Coupon artifact | Physical check | Result | Fixture / host / board used | Observation or photo reference |\n'
    printf '|---|---|---|---|---|\n'
} > "$worksheet"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Local Mechanical Bundle\n\n'
    printf 'Generated at `%s` from `%s`.\n\n' "$generated_at" "$source_scad"
    printf 'Use the STL files for quick prints and `previews/*.png` for a fast visual sanity check before sending jobs to a printer. This bundle is evidence scaffolding only; it does not close any physical-evidence row by itself.\n\n'
    printf 'Evidence rows still requiring real checks:\n\n'
    printf '%s\n' '- Host-fit against real USB-A host ports'
    printf '%s\n' '- Adjacent-port clearance for the wider body behind the USB-A nose'
    printf '%s\n' '- `MH1` / `MH2` clamp alignment against a board or board blank'
    printf '%s\n' '- Service-hatch reach with the intended probe and non-marring opening tool'
    printf '%s\n\n' '- Connector-retention load sharing after clamp/enclosure assembly'
    printf 'Record real observations in `PHYSICAL-CHECK-WORKSHEET.md`, then transfer the accepted evidence back to `hardware/shared/USB-HUB/CONNECTOR-RETENTION-VERIFY.md` and `hardware/shared/USB-HUB/MANIFEST.md`.\n'
} > "$readme"

for coupon in "${coupons[@]}"; do
    IFS='|' read -r mode filename <<<"$coupon"
    artifact="$output_dir/$filename"
    log="$output_dir/${filename%.stl}.openscad.log"
    preview="$preview_dir/${filename%.stl}.png"
    preview_log="$preview_dir/${filename%.stl}.preview.openscad.log"

    printf 'Rendering %s -> %s\n' "$mode" "$artifact"
    openscad \
        -D "export_mode=\"$mode\"" \
        -o "$artifact" \
        "$repo_root/$source_scad" \
        >"$log" 2>&1

    [[ -s "$artifact" ]] || die "OpenSCAD did not write a non-empty artifact for $mode"
    if ! grep -q 'Top level object is a 3D object (manifold)' "$log"; then
        die "OpenSCAD did not report a manifold 3D object for $mode; see $log"
    fi
    if ! grep -q 'Status:[[:space:]]*NoError' "$log"; then
        die "OpenSCAD did not report NoError for $mode; see $log"
    fi

    printf 'Rendering preview %s -> %s\n' "$mode" "$preview"
    openscad \
        --autocenter \
        --viewall \
        --imgsize=1600,1000 \
        -D "export_mode=\"$mode\"" \
        -o "$preview" \
        "$repo_root/$source_scad" \
        >"$preview_log" 2>&1

    [[ -s "$preview" ]] || die "OpenSCAD did not write a non-empty preview for $mode"
    if grep -Eq '^(ERROR|WARNING):' "$preview_log"; then
        die "OpenSCAD reported an issue for preview $mode; see $preview_log"
    fi

    bytes="$(wc -c < "$artifact" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$artifact" | awk '{ print $1 }')"
    preview_rel="previews/$(basename "$preview")"
    preview_bytes="$(wc -c < "$preview" | tr -d '[:space:]')"
    preview_sha256="$(shasum -a 256 "$preview" | awk '{ print $1 }')"
    printf '| `%s` | `%s` | %s | `%s` | `%s` | %s | `%s` | STL manifold/NoError; preview rendered |\n' \
        "$mode" "$filename" "$bytes" "$sha256" \
        "$preview_rel" "$preview_bytes" "$preview_sha256" >> "$manifest"
done

{
    printf '| `usb-hub-host-fit-coupon.stl` | USB-A shoulder seats against real host-port faces without printed body interference |  |  |  |\n'
    printf '| `usb-hub-host-fit-coupon.stl` | Wider body clears adjacent USB-A ports on real hosts |  |  |  |\n'
    printf '| `usb-hub-clamp-alignment-gauge.stl` | `MH1` / `MH2` clamp holes align against a board or board blank |  |  |  |\n'
    printf '| `usb-hub-service-hatch-reach-gauge.stl` | Probe and spudger reach the service row and hatch notch without pulling on the connector |  |  |  |\n'
    printf '| `usb-hub-validation-set.stl` | Assembled clamp/enclosure path shares connector insertion/removal load instead of relying on solder joints alone |  |  |  |\n'
    printf '\nThese generated files are print/preview scaffolding only. Transfer real observations back into `hardware/shared/USB-HUB/CONNECTOR-RETENTION-VERIFY.md` and `hardware/shared/USB-HUB/MANIFEST.md` before treating any row as closed.\n'
} >> "$worksheet"

printf 'Generated %s coupon STLs in %s\n' "${#coupons[@]}" "$output_dir"
printf 'Generated %s preview PNGs in %s\n' "${#coupons[@]}" "$preview_dir"
printf 'Manifest: %s\n' "$manifest"
printf 'Bundle README: %s\n' "$readme"
printf 'Physical check worksheet: %s\n' "$worksheet"
