#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# PowerFinger - Regenerate R30-OLED-NONE-NONE quick-print fit coupons locally.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_scad="hardware/ring/R30-OLED-NONE-NONE/cad/r30_oled_none_none_shell_blank.scad"
default_output="$repo_root/build/r30-oled-none-none-mechanical"

usage() {
    cat <<'EOF'
Usage:
  scripts/generate-r30-ring-fit-coupons.sh [output-dir]

Regenerates the active R30-OLED-NONE-NONE ring OpenSCAD quick-print fit coupon
STLs, preview PNGs, local manifests, and a blank physical-check worksheet for
the current first-board packet.

With no output directory, regenerates:
  build/r30-oled-none-none-mechanical

The generated files are local print/preview artifacts only. They do not prove
off-board service-pad access, board retention, lid pad clearance,
dome-click travel, off-board battery-service harness routing, service-lid
handling, focal distance, comfort, or RF behavior until printed and checked
against real hardware or representative fixtures.
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 2
fi

command -v openscad >/dev/null 2>&1 || die "openscad is not on PATH"

output_dir="${1:-$default_output}"
case "$output_dir" in
    /*) ;;
    *) output_dir="$repo_root/$output_dir" ;;
esac

[[ -f "$repo_root/$source_scad" ]] || die "missing OpenSCAD source: $source_scad"
[[ "$output_dir" != "$repo_root" && "$output_dir" != "/" ]] || die "refusing to export into $output_dir"

if [[ "$output_dir" == "$default_output" ]]; then
    rm -rf "$output_dir"
elif [[ -d "$output_dir" ]] && find "$output_dir" -mindepth 1 -maxdepth 1 | grep -q .; then
    die "custom output directory is not empty: $output_dir"
fi

mkdir -p "$output_dir"
preview_dir="$output_dir/previews"
mkdir -p "$preview_dir"

declare -a coupons=(
    "service_access_coupon|r30-oled-none-none-service-access-coupon.stl|J1 off-board service fixture/pogo access pocket"
    "board_retention_coupon|r30-oled-none-none-board-retention-coupon.stl|Board rails and stop lugs"
    "lid_pad_coupon|r30-oled-none-none-lid-pad-coupon.stl|Lid compression-pad channel"
    "battery_harness_coupon|r30-oled-none-none-battery-harness-coupon.stl|Off-board battery-service harness channel and service-loop relief"
    "service_lid_coupon|r30-oled-none-none-service-lid-coupon.stl|Service-lid skirt, socket, and pry path"
    "fit_coupons|r30-oled-none-none-fit-coupons.stl|Combined quick-print coupon sheet"
)

openscad_version="$(openscad --version 2>&1 | head -n 1)"
generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
manifest="$output_dir/COUPON-MANIFEST.md"
worksheet="$output_dir/PHYSICAL-CHECK-WORKSHEET.md"
readme="$output_dir/README.md"

{
    printf '<!-- SPDX-License-Identifier: CERN-OHL-S-2.0 -->\n'
    printf '# R30-OLED-NONE-NONE Mechanical Print / Preview Bundle\n\n'
    printf 'Generated by `scripts/generate-r30-ring-fit-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf '%s\n' "- Source: \`$source_scad\`"
    printf '%s\n' "- OpenSCAD: \`$openscad_version\`"
    printf '%s\n\n' "- Scope: generated STL and PNG preview artifacts only; no physical fit, stackup, focal-distance, comfort, or RF measurements are claimed here."
    printf '| Export mode | Fit unknown targeted | Print artifact | Print bytes | Print SHA-256 | Preview artifact | Preview bytes | Preview SHA-256 | OpenSCAD result |\n'
    printf '|---|---|---|---:|---|---|---:|---|---|\n'
} > "$manifest"

{
    printf '<!-- SPDX-License-Identifier: CERN-OHL-S-2.0 -->\n'
    printf '# R30-OLED-NONE-NONE Physical Coupon Check Worksheet\n\n'
    printf 'Generated by `scripts/generate-r30-ring-fit-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf 'Use this worksheet after printing the generated STLs. Leave rows blank until a real board, board blank, service fixture, battery harness, lid, service tool, or printed coupon has been checked. Do not mark a pass from CAD generation or PNG preview alone.\n\n'
    printf '| Coupon artifact | Physical check | Result | Fixture / board / tool used | Observation or photo reference |\n'
    printf '|---|---|---|---|---|\n'
} > "$worksheet"

{
    printf '<!-- SPDX-License-Identifier: CERN-OHL-S-2.0 -->\n'
    printf '# R30-OLED-NONE-NONE Local Mechanical Bundle\n\n'
    printf 'Generated at `%s` from `%s`.\n\n' "$generated_at" "$source_scad"
    printf 'Use the STL files for quick prints and `previews/*.png` for a fast visual sanity check before sending jobs to a printer. This bundle is evidence scaffolding only; it does not close any physical-evidence row by itself.\n\n'
    printf 'Evidence rows still requiring real checks:\n\n'
    printf '%s\n' '- `service_access_coupon` J1 service-pad fixture/pogo access without shell or board-rail loading'
    printf '%s\n' '- `43 x 18 mm` board slide, stop repeatability, and hand lift-out'
    printf '%s\n' '- Lid pad clearance against intended board-edge zones only'
    printf '%s\n' '- Off-board `J_BAT` battery-service harness bend, service loop, and top lift-out path'
    printf '%s\n' '- Service-lid skirt, screw, and pry-removal handling'
    printf '%s\n\n' '- Full-shell stackup, focal distance, RF, comfort, and click actuation'
    printf 'Record real observations in `PHYSICAL-CHECK-WORKSHEET.md`, then transfer accepted evidence back to `hardware/ring/R30-OLED-NONE-NONE/STACKUP-VERIFY.md` and `hardware/ring/R30-OLED-NONE-NONE/MANIFEST.md`.\n'
} > "$readme"

for coupon in "${coupons[@]}"; do
    IFS='|' read -r mode filename target <<<"$coupon"
    artifact="$output_dir/$filename"
    log="$output_dir/${filename%.stl}.openscad.log"
    preview="$preview_dir/${filename%.stl}.png"
    preview_log="$preview_dir/${filename%.stl}.preview.openscad.log"

    printf 'Rendering %s -> %s\n' "$mode" "$artifact"
    openscad \
        -D "export_mode=\"$mode\"" \
        -o "$artifact" \
        "$repo_root/$source_scad" \
        >"$log" 2>&1

    [[ -s "$artifact" ]] || die "OpenSCAD did not write a non-empty artifact for $mode"
    if ! grep -q 'Top level object is a 3D object (manifold)' "$log"; then
        die "OpenSCAD did not report a manifold 3D object for $mode; see $log"
    fi
    if ! grep -q 'Status:[[:space:]]*NoError' "$log"; then
        die "OpenSCAD did not report NoError for $mode; see $log"
    fi

    printf 'Rendering preview %s -> %s\n' "$mode" "$preview"
    openscad \
        --autocenter \
        --viewall \
        --imgsize=1600,1000 \
        -D "export_mode=\"$mode\"" \
        -o "$preview" \
        "$repo_root/$source_scad" \
        >"$preview_log" 2>&1

    [[ -s "$preview" ]] || die "OpenSCAD did not write a non-empty preview for $mode"
    if grep -Eq '^(ERROR|WARNING):' "$preview_log"; then
        die "OpenSCAD reported an issue for preview $mode; see $preview_log"
    fi

    bytes="$(wc -c < "$artifact" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$artifact" | awk '{ print $1 }')"
    preview_rel="previews/$(basename "$preview")"
    preview_bytes="$(wc -c < "$preview" | tr -d '[:space:]')"
    preview_sha256="$(shasum -a 256 "$preview" | awk '{ print $1 }')"
    printf '| `%s` | %s | `%s` | %s | `%s` | `%s` | %s | `%s` | STL manifold/NoError; preview rendered |\n' \
        "$mode" "$target" "$filename" "$bytes" "$sha256" \
        "$preview_rel" "$preview_bytes" "$preview_sha256" >> "$manifest"
done

{
    printf '| `r30-oled-none-none-service-access-coupon.stl` | Service-access coupon lets the J1 service fixture/pogo path reach pads without binding, levering the board edge, or scraping the shell opening |  |  |  |\n'
    printf '| `r30-oled-none-none-board-retention-coupon.stl` | `43 x 18 mm` board or blank slides onto rails, stops repeatably, and lifts out by hand |  |  |  |\n'
    printf '| `r30-oled-none-none-lid-pad-coupon.stl` | Lid pads contact only intended board-edge keep-out zones and do not trap components |  |  |  |\n'
    printf '| `r30-oled-none-none-battery-harness-coupon.stl` | Off-board `J_BAT` harness and service loop clear the seam during protected-cell lift-out |  |  |  |\n'
    printf '| `r30-oled-none-none-service-lid-coupon.stl` | Lid/skirt/pry path reopens without destructive flex, tiny-tool dependence, or loose-hardware handling that blocks accessibility |  |  |  |\n'
    printf '| `r30-oled-none-none-fit-coupons.stl` | Combined coupon print exposes no obvious generation-time geometry mismatch before individual physical checks |  |  |  |\n'
    printf '\nThese generated files are print/preview scaffolding only. Transfer real observations back into `hardware/ring/R30-OLED-NONE-NONE/STACKUP-VERIFY.md` and `hardware/ring/R30-OLED-NONE-NONE/MANIFEST.md` before treating any row as closed.\n'
} >> "$worksheet"

printf 'Generated %s coupon STLs in %s\n' "${#coupons[@]}" "$output_dir"
printf 'Generated %s preview PNGs in %s\n' "${#coupons[@]}" "$preview_dir"
printf 'Manifest: %s\n' "$manifest"
printf 'Bundle README: %s\n' "$readme"
printf 'Physical check worksheet: %s\n' "$worksheet"
