#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# PowerFinger - Regenerate USB-HUB quick-print validation coupons locally.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_scad="hardware/shared/USB-HUB/cad/usb_hub_enclosure_blank.scad"
default_output="$repo_root/build/usb-hub-mechanical"

usage() {
    cat <<'EOF'
Usage:
  scripts/generate-usb-hub-validation-coupons.sh [output-dir]

Regenerates the USB-HUB OpenSCAD validation coupon STLs, preview PNGs, local
manifests, a FIRST-PRINT proof-capture packet, and physical-check worksheet
scaffolding for the next direct-plug hub check.

With no output directory, regenerates:
  build/usb-hub-mechanical

The generated files are local print/preview artifacts only. They do not prove
physical USB-A seating, adjacent-port clearance, clamp loading, hatch reach, or
connector strain until printed and checked against real hardware.

After real checks are recorded in a generated worksheet, ingest the USB-HUB rows
back into the checked-in result ledger with:
  scripts/ingest-usb-hub-coupon-results.py <PHYSICAL-CHECK-WORKSHEET.md>
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 2
fi

command -v openscad >/dev/null 2>&1 || die "openscad is not on PATH"

output_dir="${1:-$default_output}"
case "$output_dir" in
    /*) ;;
    *) output_dir="$repo_root/$output_dir" ;;
esac

[[ -f "$repo_root/$source_scad" ]] || die "missing OpenSCAD source: $source_scad"
[[ "$output_dir" != "$repo_root" && "$output_dir" != "/" ]] || die "refusing to export into $output_dir"

if [[ "$output_dir" == "$default_output" ]]; then
    rm -rf "$output_dir"
elif [[ -d "$output_dir" ]] && find "$output_dir" -mindepth 1 -maxdepth 1 | grep -q .; then
    die "custom output directory is not empty: $output_dir"
fi

mkdir -p "$output_dir"
preview_dir="$output_dir/previews"
mkdir -p "$preview_dir"

declare -a coupons=(
    "host_fit_coupon|usb-hub-host-fit-coupon.stl"
    "clamp_alignment_gauge|usb-hub-clamp-alignment-gauge.stl"
    "service_hatch_reach_gauge|usb-hub-service-hatch-reach-gauge.stl"
    "validation_set|usb-hub-validation-set.stl"
)

openscad_version="$(openscad --version 2>&1 | head -n 1)"
generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
manifest="$output_dir/COUPON-MANIFEST.md"
worksheet="$output_dir/PHYSICAL-CHECK-WORKSHEET.md"
readme="$output_dir/README.md"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Mechanical Print / Preview Bundle\n\n'
    printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf '%s\n' "- Source: \`$source_scad\`"
    printf '%s\n' "- OpenSCAD: \`$openscad_version\`"
    printf '%s\n' "- Scope: generated STL and PNG preview artifacts only; no physical fit, strain, or clearance measurements are claimed here."
    printf '%s\n\n' "- First-print packet: \`FIRST-PRINT/\` collects the concrete first physical print set and blank proof-capture worksheet."
    printf '| Export mode | Print artifact | Print bytes | Print SHA-256 | Preview artifact | Preview bytes | Preview SHA-256 | OpenSCAD result |\n'
    printf '|---|---|---:|---|---|---:|---|---|\n'
} > "$manifest"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Physical Coupon Check Worksheet\n\n'
    printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
    printf 'Use this worksheet after printing the generated STLs. Leave rows blank until a real board, board blank, host port, tool, or printed coupon has been checked. Do not mark a pass from CAD generation or PNG preview alone.\n\n'
    printf 'Accepted `Result` values are `pass`, `fail`, `partial`, and `blocked`. Any non-blank result must include the fixture, host, board, or tool used plus an observation or photo reference. Then run `scripts/ingest-usb-hub-coupon-results.py %s` from the repository root.\n\n' "${worksheet#$repo_root/}"
    printf '| Coupon artifact | Physical check | Result | Fixture / host / board used | Observation or photo reference |\n'
    printf '|---|---|---|---|---|\n'
} > "$worksheet"

{
    printf '<!-- SPDX-License-Identifier: MIT -->\n'
    printf '# USB-HUB Local Mechanical Bundle\n\n'
    printf 'Generated at `%s` from `%s`.\n\n' "$generated_at" "$source_scad"
    printf 'Use the STL files for quick prints and `previews/*.png` for a fast visual sanity check before sending jobs to a printer. This bundle is evidence scaffolding only; it does not close any physical-evidence row by itself.\n\n'
    printf 'Evidence rows still requiring real checks:\n\n'
    printf '%s\n' '- Host-fit against real USB-A host ports'
    printf '%s\n' '- Adjacent-port clearance for the wider body behind the USB-A nose'
    printf '%s\n' '- `MH1` / `MH2` clamp alignment against a board or board blank'
    printf '%s\n' '- Service-hatch reach with the intended probe and non-marring opening tool'
    printf '%s\n\n' '- Connector-retention load sharing after clamp/enclosure assembly'
    printf 'For the concrete first physical print set, start with `FIRST-PRINT/`. Record real observations in `PHYSICAL-CHECK-WORKSHEET.md` or `FIRST-PRINT/PHYSICAL-CHECK-WORKSHEET.md`, then run `scripts/ingest-usb-hub-coupon-results.py` on the filled worksheet so accepted evidence lands in `hardware/shared/USB-HUB/COUPON-RESULTS.md`.\n'
} > "$readme"

for coupon in "${coupons[@]}"; do
    IFS='|' read -r mode filename <<<"$coupon"
    artifact="$output_dir/$filename"
    log="$output_dir/${filename%.stl}.openscad.log"
    preview="$preview_dir/${filename%.stl}.png"
    preview_log="$preview_dir/${filename%.stl}.preview.openscad.log"

    printf 'Rendering %s -> %s\n' "$mode" "$artifact"
    openscad \
        -D "export_mode=\"$mode\"" \
        -o "$artifact" \
        "$repo_root/$source_scad" \
        >"$log" 2>&1

    [[ -s "$artifact" ]] || die "OpenSCAD did not write a non-empty artifact for $mode"
    if ! grep -q 'Top level object is a 3D object (manifold)' "$log"; then
        die "OpenSCAD did not report a manifold 3D object for $mode; see $log"
    fi
    if ! grep -q 'Status:[[:space:]]*NoError' "$log"; then
        die "OpenSCAD did not report NoError for $mode; see $log"
    fi

    printf 'Rendering preview %s -> %s\n' "$mode" "$preview"
    openscad \
        --autocenter \
        --viewall \
        --imgsize=1600,1000 \
        -D "export_mode=\"$mode\"" \
        -o "$preview" \
        "$repo_root/$source_scad" \
        >"$preview_log" 2>&1

    [[ -s "$preview" ]] || die "OpenSCAD did not write a non-empty preview for $mode"
    if grep -Eq '^(ERROR|WARNING):' "$preview_log"; then
        die "OpenSCAD reported an issue for preview $mode; see $preview_log"
    fi

    bytes="$(wc -c < "$artifact" | tr -d '[:space:]')"
    sha256="$(shasum -a 256 "$artifact" | awk '{ print $1 }')"
    preview_rel="previews/$(basename "$preview")"
    preview_bytes="$(wc -c < "$preview" | tr -d '[:space:]')"
    preview_sha256="$(shasum -a 256 "$preview" | awk '{ print $1 }')"
    printf '| `%s` | `%s` | %s | `%s` | `%s` | %s | `%s` | STL manifold/NoError; preview rendered |\n' \
        "$mode" "$filename" "$bytes" "$sha256" \
        "$preview_rel" "$preview_bytes" "$preview_sha256" >> "$manifest"
done

{
    printf '| `usb-hub-host-fit-coupon.stl` | USB-A shoulder seats against real host-port faces without printed body interference |  |  |  |\n'
    printf '| `usb-hub-host-fit-coupon.stl` | Wider body clears adjacent USB-A ports on real hosts |  |  |  |\n'
    printf '| `usb-hub-clamp-alignment-gauge.stl` | `MH1` / `MH2` clamp holes align against a board or board blank |  |  |  |\n'
    printf '| `usb-hub-service-hatch-reach-gauge.stl` | Probe and spudger reach the service row and hatch notch without pulling on the connector |  |  |  |\n'
    printf '| `usb-hub-validation-set.stl` | Assembled clamp/enclosure path shares connector insertion/removal load instead of relying on solder joints alone |  |  |  |\n'
    printf '\nThese generated files are print/preview scaffolding only. Ingest real observations into `hardware/shared/USB-HUB/COUPON-RESULTS.md` with `scripts/ingest-usb-hub-coupon-results.py %s` before treating any row as closed.\n' "${worksheet#$repo_root/}"
} >> "$worksheet"

file_sha256() {
    shasum -a 256 "$1" | awk '{ print $1 }'
}

write_file_index_row() {
    local root_dir="$1"
    local generated_file="$2"
    local rel_path="${generated_file#$root_dir/}"
    local bytes
    local sha256

    bytes="$(wc -c < "$generated_file" | tr -d '[:space:]')"
    sha256="$(file_sha256 "$generated_file")"
    printf '| `%s` | %s | `%s` |\n' "$rel_path" "$bytes" "$sha256"
}

copy_first_print_file() {
    local rel_path="$1"
    local src="$output_dir/$rel_path"
    local dest="$first_print_output/$rel_path"

    [[ -f "$src" ]] || die "missing first-print source: $rel_path"
    mkdir -p "$(dirname "$dest")"
    cp -p "$src" "$dest"
}

assert_file_contains() {
    local file="$1"
    local pattern="$2"

    grep -Fq "$pattern" "$file" || die "expected $file to contain: $pattern"
}

assemble_first_print_packet() {
    first_print_output="$output_dir/FIRST-PRINT"
    rm -rf "$first_print_output"
    mkdir -p "$first_print_output"

    local -a first_print_assets=(
        "usb-hub-host-fit-coupon.stl"
        "usb-hub-host-fit-coupon.openscad.log"
        "previews/usb-hub-host-fit-coupon.png"
        "previews/usb-hub-host-fit-coupon.preview.openscad.log"
        "usb-hub-clamp-alignment-gauge.stl"
        "usb-hub-clamp-alignment-gauge.openscad.log"
        "previews/usb-hub-clamp-alignment-gauge.png"
        "previews/usb-hub-clamp-alignment-gauge.preview.openscad.log"
        "usb-hub-service-hatch-reach-gauge.stl"
        "usb-hub-service-hatch-reach-gauge.openscad.log"
        "previews/usb-hub-service-hatch-reach-gauge.png"
        "previews/usb-hub-service-hatch-reach-gauge.preview.openscad.log"
        "usb-hub-validation-set.stl"
        "usb-hub-validation-set.openscad.log"
        "previews/usb-hub-validation-set.png"
        "previews/usb-hub-validation-set.preview.openscad.log"
    )

    local rel_path
    for rel_path in "${first_print_assets[@]}"; do
        copy_first_print_file "$rel_path"
    done

    {
        printf '<!-- SPDX-License-Identifier: MIT -->\n'
        printf '# USB-HUB First-Print Proof-Capture Packet\n\n'
        printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
        printf 'Use this folder as the first print queue for the direct-plug hub mechanical proof pass. It collects the generated STLs, preview PNGs, OpenSCAD logs, manifest, README, and blank worksheet needed to capture host-fit, adjacent-port clearance, clamp alignment, service-hatch reach, and connector-retention observations.\n\n'
        printf 'This is generated evidence scaffolding only. Do not mark any row as passed until printed coupons are checked against real host ports, a board or board blank, intended service tools, and the connector/clamp assembly path.\n\n'
        printf '%s\n' '- Print `usb-hub-host-fit-coupon.stl` first for USB-A shoulder seating and adjacent-port clearance.'
        printf '%s\n' '- Print `usb-hub-clamp-alignment-gauge.stl` next for `MH1` / `MH2` alignment.'
        printf '%s\n' '- Print `usb-hub-service-hatch-reach-gauge.stl` for probe and hatch access.'
        printf '%s\n' '- Print `usb-hub-validation-set.stl` when ready to capture connector-retention/load-sharing observations.'
        printf '\nAfter filling real observations, run `scripts/ingest-usb-hub-coupon-results.py %s` from the repository root. That updates `hardware/shared/USB-HUB/COUPON-RESULTS.md`; use that ledger before changing `CONNECTOR-RETENTION-VERIFY.md` or `MANIFEST.md` closure state.\n' "${first_print_output#$repo_root/}/PHYSICAL-CHECK-WORKSHEET.md"
    } > "$first_print_output/README.md"

    {
        printf '<!-- SPDX-License-Identifier: MIT -->\n'
        printf '# USB-HUB First-Print Physical Check Worksheet (Blank)\n\n'
        printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
        printf 'Leave result fields blank until the printed coupons have been checked against real hosts, plugs, a board or board blank, clamp hardware, and intended service tools. CAD generation, manifold OpenSCAD output, and PNG previews do not count as physical measurement.\n\n'
        printf 'Accepted `Result` values are `pass`, `fail`, `partial`, and `blocked`. Any non-blank result must include the fixture, host, board, or tool used plus an observation or photo reference. Then run `scripts/ingest-usb-hub-coupon-results.py %s` from the repository root.\n\n' "${first_print_output#$repo_root/}/PHYSICAL-CHECK-WORKSHEET.md"
        printf '| Coupon artifact | Physical check | Result | Fixture / host / board used | Observation or photo reference |\n'
        printf '|---|---|---|---|---|\n'
        printf '| `usb-hub-host-fit-coupon.stl` | USB-A shoulder seats against real host-port faces without printed body interference |  |  |  |\n'
        printf '| `usb-hub-host-fit-coupon.stl` | Wider body clears adjacent USB-A ports on real hosts |  |  |  |\n'
        printf '| `usb-hub-clamp-alignment-gauge.stl` | `MH1` / `MH2` clamp holes align against a board or board blank |  |  |  |\n'
        printf '| `usb-hub-service-hatch-reach-gauge.stl` | Probe and non-marring opener reach the service row and hatch notch without pulling on the connector |  |  |  |\n'
        printf '| `usb-hub-validation-set.stl` | Clamp/enclosure path captures connector insertion/removal load instead of relying on solder joints alone |  |  |  |\n'
        printf '\nThis worksheet starts blank by design; generated files are not measured evidence.\n'
    } > "$first_print_output/PHYSICAL-CHECK-WORKSHEET.md"

    first_print_manifest="$first_print_output/PACKET-MANIFEST.md"
    {
        printf '<!-- SPDX-License-Identifier: MIT -->\n'
        printf '# USB-HUB First-Print Packet Manifest\n\n'
        printf 'Generated by `scripts/generate-usb-hub-validation-coupons.sh` at `%s`.\n\n' "$generated_at"
        printf 'Scope: the four selected USB-HUB first-print STL coupons, matching previews, OpenSCAD logs, README, and a blank worksheet for host-fit, adjacent-port clearance, clamp alignment, service-hatch reach, and connector-retention capture. This is a generated print packet, not measured physical evidence.\n\n'
        printf '| Path | Bytes | SHA-256 |\n'
        printf '|---|---:|---|\n'
        while IFS= read -r generated_file; do
            write_file_index_row "$first_print_output" "$generated_file"
        done < <(find "$first_print_output" -type f ! -path "$first_print_manifest" | LC_ALL=C sort)
    } > "$first_print_manifest"

    local actual_file_count
    actual_file_count="$(find "$first_print_output" -type f | wc -l | tr -d '[:space:]')"
    [[ "$actual_file_count" == "19" ]] || die "first-print file count drift: expected 19, found $actual_file_count"
    assert_file_contains "$first_print_output/README.md" "generated evidence scaffolding only"
    assert_file_contains "$first_print_output/PHYSICAL-CHECK-WORKSHEET.md" "CAD generation, manifold OpenSCAD output, and PNG previews do not count as physical measurement"
    assert_file_contains "$first_print_output/PACKET-MANIFEST.md" "not measured physical evidence"
}

assemble_first_print_packet

printf 'Generated %s coupon STLs in %s\n' "${#coupons[@]}" "$output_dir"
printf 'Generated %s preview PNGs in %s\n' "${#coupons[@]}" "$preview_dir"
printf 'First-print packet: %s\n' "$output_dir/FIRST-PRINT"
printf 'Manifest: %s\n' "$manifest"
printf 'Bundle README: %s\n' "$readme"
printf 'Physical check worksheet: %s\n' "$worksheet"
